name = "CMU Courses"
slug = "cmucourses"
website-slug = "courses"
description = "Web application to browse course information and build schedules"
contributing-guide = """"
Reach out to Anish Pallati on Slack or an.ish on Discord for more information.
"""
maintainers = [
    "xavilien",
    "ap-1",
    "yl25946",
]
contributors = [
    "xavilien",
    "ap-1",
    "yl25946",
    "maybe-yiyi",
]
repos = [
    "ScottyLabs/cmucourses",       # Old CMUCourses
    "ScottyLabs/courses-frontend", # New CMUCourses frontend
    "ScottyLabs/courses-backend",  # New CMUCourses backend
    "ScottyLabs/courses-scraper",  # Scraping information on CMU Courses
    "ScottyLabs/courses-api",      # API that gives course information
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = true
create-oidc-clients = true
secrets-population-layout = "none"
