name = "DevOps"
slug = "devops"
description = """
Devops is a team that works on team management, hosting,
and storage systems for almost all projects. We work in
close cooperation with other teams to set up the features
they need to run their projects.
"""
contributing-guide = """
Message Ryan Li on Slack or thesuperRL on Discord if you are interested in joining the team!
"""
maintainers = [
    "thesuperRL",
    "ap-1",
    "Yuxiang-Huang",
]
contributors = [
    "thesuperRL",
    "ap-1",
    "Yuxiang-Huang",
    "Gostmeaper",
]
repos = [
    "governance",
    "infrastructure",
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = false
create-oidc-clients = false
secrets-population-layout = "none"
