[[rule]]
include = ["contributors/*.toml", "repos/*.toml", "teams/*.toml"]

[rule.formatting]
array_auto_expand = true
array_trailing_comma = true
column_width = 0

[[rule]]
include = ["contributors/*.toml"]

[rule.schema]
path = "./meta/schemas/contributor.schema.json"
enabled = true

[[rule]]
include = ["repos/*.toml"]

[rule.schema]
path = "./meta/schemas/repo.schema.json"
enabled = true

[[rule]]
include = ["teams/*.toml"]

[rule.schema]
path = "./meta/schemas/team.schema.json"
enabled = true
